server:
  servlet:
    contextPath: /calc-age
  error:
    include-message: always

spring:
  application:
    name: talent-ql-age
  profiles:
    active: local

app:
  version: 1
  name: Age Calculation
  description: Simple endppoint to calculate Age

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,loggers
  endpoint:
    loggers:
      enabled: true
    prometheus:
      enabled: true

bucket4j:
  enabled: true
  filters:
    - cache-name: buckets
      url: .*
      http-response-body: "{ \"status\": 429, \"error\": \"Too Many Requests\", \"message\": \"You have exhausted your API Request Quota\" }"
      rate-limits:
        - bandwidths:
            - capacity: 3
              time: 1
              unit: minutes



